### ISSUE TITLE
Dockerize App

### ISSUE THREAD

**Issue by Eolran** [Corentin-kzk/GameOfGo#2]
We need our app to : 
- Run a front developed in a front framework (to be decided)
- Run a back-end server developed in Django
- Run a Database developed in MongoDB

**Comment by Eolran** [comment]
Starting clean image for mongoDB :
```yml
version: '3.3'

services:

  mongo:
    container_name: docker_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
```
Taken from [**Septentrion/CoursDjango/MongoDB**](https://github.com/Septentrion/CoursDjango/blob/main/Support_noSQL/MongoDB/docker-compose.yml)
